# Production CI/CD Pipeline
name: Deploy to Production

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NODE_VERSION: '20'
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run TypeScript check
        run: npm run check
      
      - name: Build application
        run: npm run build
      
      - name: Run health check test
        run: |
          echo "Starting development server..."
          timeout 60s npm run dev:server &
          SERVER_PID=$!
          
          echo "Waiting for server to start..."
          sleep 15
          
          echo "Testing health endpoint..."
          for i in {1..10}; do
            echo "Attempt $i: Testing /health endpoint..."
            if curl -f http://localhost:5000/health; then
              echo "✅ Health check passed!"
              break
            else
              echo "❌ Health check failed, attempt $i"
              if [ $i -eq 10 ]; then
                echo "❌ Health check failed after 10 attempts"
                exit 1
              fi
              sleep 3
            fi
          done
          
          echo "Cleaning up server..."
          kill $SERVER_PID 2>/dev/null || true
          wait $SERVER_PID 2>/dev/null || true